//--Summary:
//  Create a program that utilizes goroutines to run the provided calculation
//  function on a number of jobs. The results from the goroutines must be
//  communicated back to the main thread using a channel, and then added
//  together.
//
//--Requirements:
//* Run `longCalculation` for each job generated by the `makeJobs` function
//* Each job must be run in a separate goroutine
//* The result from `longCalculation` must be provided to the main function
//  using a channel
//* Sum the results from each job to generate a final result, and print it
//  to the terminal

package main

import (
	"fmt"
	"math/rand"
	"sync"
	"time"
)

type Job int

var rng = rand.New(rand.NewSource(time.Now().UnixNano()))

func longCalculation(i Job) int {
	duration := time.Duration(rng.Intn(1000)) * time.Millisecond
	time.Sleep(duration)

	fmt.Printf("Job %d complete in %v\n", i, duration)

	return int(i) * 30
}

func makeJobs() []Job {
	jobs := make([]Job, 0, 25)

	for i := 0; i < 25; i++ {
		jobs = append(jobs, Job(rng.Intn(1000)))
	}

	return jobs
}

func main() {
	jobs := makeJobs()

	results := make(chan int)
	var wg sync.WaitGroup

	for _, job := range jobs {
		wg.Add(1)

		go func(j Job) {
			defer wg.Done()

			result := longCalculation(j)
			results <- result
		}(job)
	}

	go func() {
		wg.Wait()
		close(results)
	}()

	total := 0

	for result := range results {
		total += result
	}

	fmt.Printf("Sum: %d\n", total)
}
